spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=postgres
spring.datasource.password=Omjadhav@0809

jwt.secret=${JWT_SECRET:my-local-taskflow-secret-key-12345678901234567890}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true