# # spring.application.name=taskflow-api

# # Change the default port (8080) if you want
# server.port=8080

# # App name — shows up in logs
# spring.application.name=taskflow-api

# # We'll add DB connection settings here Day 10-13:
# # spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
# # spring.datasource.username=postgres
# # spring.datasource.password=yourpassword

spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=postgres
spring.datasource.password=Omjadhav@0809

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
